<a href="https://colab.research.google.com/github/MaxineMwangi/flyrank/blob/main/work/notebooks/w02_ml_task_framing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MaxineMwangi/flyrank/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

One row represents one content item/page. The columns describe that page's characteristics and performance.

## 1) My lane as an ML task

**Task type: Ranking**

I want to rank content pages by their potential priority for review or refresh. The goal is to help a content team decide which pages should be investigated first rather than treating every page equally.

In [19]:
# Check how many unique content items we have
print("Number of content items:", df["content_id"].nunique())

# Show a few pages that could be ranked
display(
    df[["content_id", "search_volume", "impressions_90d", "ctr"]]
    .head(10)
)

Number of content items: 30000

             content_id  search_volume  impressions_90d   ctr
0  content_304f48230142           10.0             3803  0.76
1  content_a1fb4e703a9e           90.0            15320  0.05
2  content_9aa793d4d895            0.0            12581  0.09
3  content_331d6c4de07b           10.0            11751  0.49
4  content_d99b7a2d90ca            0.0            19140  0.13
5  content_d4084a4bc775          720.0             3970  0.03
6  content_9a34b442b552            0.0               20  0.00
7  content_a63219c6e95a          590.0             1724  0.06
8  content_5e6c160719bc            0.0            32574  0.09
9  content_c27558df2b0c            0.0             1240  0.16

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

Target/proxy: A priority score representing the relative opportunity to prioritize existing content for review/refresh, informed by observable search demand and performance signals.

## 2) Target or proxy

**Proxy: content refresh priority**

The proxy represents the relative opportunity to prioritize a content page for review or refresh. It is informed by observable page-level signals such as search demand, search visibility, and click performance. No single metric fully represents refresh opportunity, so multiple signals can be considered together when producing the ranking.

In [20]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
proxy_signals = [
    "search_volume",
    "impressions_90d",
    "clicks_90d",
    "ctr"
]

display(df[proxy_signals].describe().T)

,count,mean,std,min,25%,50%,75%,max
search_volume,27532.0,158.882391,1518.270825,0.0,0.0,10.00,20.00,74000.0
impressions_90d,30000.0,5200.366300,16838.019547,1.0,81.0,731.00,3615.25,517715.0
clicks_90d,30000.0,16.097333,75.076958,0.0,0.0,1.00,7.00,4178.0
ctr,30000.0,0.510733,3.279162,0.0,0.0,0.07,0.29,100.0

In [21]:
display(
    df[
        ["content_id", "search_volume", "impressions_90d", "clicks_90d", "ctr"]
    ].sort_values(
        ["impressions_90d", "search_volume"],
        ascending=False
    ).head(10)
)

                 content_id  search_volume  impressions_90d  clicks_90d   ctr
6653   content_5fe46e04994d         1900.0           517715         741  0.14
17812  content_aaef01a50def         4400.0           517109        1270  0.25
26844  content_8c19996aa890           70.0           509252         785  0.15
19636  content_2cb567c3c89b            0.0           497727         487  0.10
21819  content_4c36c775b818           40.0           463103        1889  0.41
29400  content_2dba2b1f9536            0.0           443434         910  0.21
29879  content_1a9e894be2e2           70.0           416180         944  0.23
13537  content_2c2606c5d176          590.0           347399        1854  0.53
18870  content_db5989a78dd3          110.0           345111         733  0.21
14090  content_44e481c8f55b           20.0           312694        2032  0.65

## 3. Success metric

*One metric you can defend. What number means 'good'?*

## 3) Success metric

**Success metric: Precision@K**

Precision@K is appropriate because the content team has limited resources and will focus on the highest-ranked pages first. We therefore care most about whether the pages near the top of the ranking are genuinely useful refresh opportunities. K can represent the number of pages the team has capacity to review or refresh.

In [22]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
K = 100

print(f"Evaluation plan: assess the top {K} ranked pages.")
print("Metric: Precision@K")

Evaluation plan: assess the top 100 ranked pages.
Metric: Precision@K

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

## 4) The unit of analysis

**One row = one content item/page.**

Each row represents an individual piece of content identified by `content_id`. The remaining columns describe characteristics and performance of that content, including search demand, impressions, clicks, CTR, position, engagement, freshness, and recent trends.

The dataframe above shows examples of individual content items and their associated attributes.

In [23]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

display(df.head())

Shape: (30000, 44)

Columns:
['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [24]:
print("Unique content IDs:", df["content_id"].nunique())
print("Rows:", len(df))

Unique content IDs: 30000
Rows: 30000

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

## 5) Why ML beats a fixed rule here

A fixed rule, such as prioritizing every page with a CTR below a particular threshold, would treat one metric as the main decision factor. However, refresh priority can depend on several signals at the same time, including search demand, impressions, clicks, CTR, position, and content freshness.

These signals can interact in ways that are difficult to capture with one manually chosen rule. An ML-based ranking approach could learn patterns across multiple signals and produce a more flexible prioritization of pages.

The output would support a content action: the team could review the highest-ranked pages first and decide which ones are worth refreshing.

In [25]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
low_ctr = df[df["ctr"] < 1]

print("Pages with CTR < 1%:", len(low_ctr))

display(
    low_ctr[
        ["content_id", "search_volume", "impressions_90d", "clicks_90d", "ctr"]
    ]
    .sort_values("impressions_90d", ascending=False)
    .head(10)
)

Pages with CTR < 1%: 28291

                 content_id  search_volume  impressions_90d  clicks_90d   ctr
6653   content_5fe46e04994d         1900.0           517715         741  0.14
17812  content_aaef01a50def         4400.0           517109        1270  0.25
26844  content_8c19996aa890           70.0           509252         785  0.15
19636  content_2cb567c3c89b            0.0           497727         487  0.10
21819  content_4c36c775b818           40.0           463103        1889  0.41
29400  content_2dba2b1f9536            0.0           443434         910  0.21
29879  content_1a9e894be2e2           70.0           416180         944  0.23
13537  content_2c2606c5d176          590.0           347399        1854  0.53
18870  content_db5989a78dd3          110.0           345111         733  0.21
14090  content_44e481c8f55b           20.0           312694        2032  0.65

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.